--run as SYS
CREATE USER SO_MON
  IDENTIFIED BY SO_MON
  DEFAULT TABLESPACE TBS5
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for SO_MON 
  GRANT SELECT_CATALOG_ROLE TO SO_MON;
  GRANT CONNECT TO SO_MON;
  GRANT RESOURCE TO SO_MON;
  ALTER USER SO_MON DEFAULT ROLE CONNECT, RESOURCE;
  -- 11 System Privileges for SO_MON 
  GRANT DEBUG CONNECT SESSION TO SO_MON;
  GRANT UNLIMITED TABLESPACE TO SO_MON;
  GRANT QUERY REWRITE TO SO_MON;
  GRANT DROP ANY VIEW TO SO_MON;
  GRANT CREATE TABLE TO SO_MON;
  GRANT DEBUG ANY PROCEDURE TO SO_MON;
  GRANT CREATE DATABASE LINK TO SO_MON WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO SO_MON;
  GRANT CREATE ANY INDEX TO SO_MON;
  GRANT GLOBAL QUERY REWRITE TO SO_MON;
  GRANT CREATE ANY PROCEDURE TO SO_MON;
  -- 2 Object Privileges for SO_MON 
    GRANT READ, WRITE ON DIRECTORY SYS.DATA_PUMP_DIR TO SO_MON;

 
 GRANT DBA TO SO_MON WITH ADMIN OPTION ;

GRANT SELECT ON SYS.GV_$SESSION TO SO_MON;

GRANT SELECT ON SYS.GV_$SQL TO SO_MON;

GRANT SELECT ON SYS.GV_$OPEN_CURSOR TO SO_MON;

GRANT SELECT ON SYS.GV_$SESSION_EVENT TO SO_MON;

GRANT SELECT ON SYS.GV_$SESSION_longops TO SO_MON;

GRANT SELECT ON SYS.gv_$sysstat TO SO_MON;

GRANT SELECT ON SYS.DBA_TABLES TO SO_MON;

--added 5/28/2015
grant select on dba_data_files to SO_MON;

grant select on dba_segments  to SO_MON;

grant select on GV_$SEGMENT_STATISTICS to SO_MON;

grant select on v_$instance  to SO_MON;

grant select on v$diag_alert_ext to SO_MON;

--added on 7/13

grant select on v_$sql to SO_MON;

grant select on v_$sql_plan to SO_MON;

grant select on sys.gv_$instance to so_mon; 

-- added 7/24

grant select on gv_$sqlarea to SO_MON;

grant select on gv_$process to SO_MON;