alter table so_mon.user_commits add INT_VALUE number;

CREATE OR REPLACE TRIGGER SO_MON.TI_USER_COMMITS BEFORE INSERT ON SO_MON.USER_COMMITS REFERENCING NEW AS NEWROW FOR EACH ROW
declare
PRAGMA AUTONOMOUS_TRANSACTION;
T_RECCHECK NUMBER;
BEGIN
SELECT NVL(SUM_VALUE,0) INTO T_RECCHECK FROM SO_MON.USER_COMMITS WHERE SERIAL_NUM = :NEWROW.SERIAL_NUM - 1;
IF T_RECCHECK NOT IN (0)  THEN
    :NEWROW.INT_VALUE := :NEWROW.SUM_VALUE - T_RECCHECK;
    commit;
END IF;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/
